platform :ios, '11.0'

use_frameworks!

target 'SJFluidSegmentedControl_Example' do
  pod 'SJFluidSegmentedControl', :path => '../'

  target 'SJFluidSegmentedControl_Tests' do
    inherit! :search_paths
    
  end
end
